### ISSUE TITLE
VSCode doesn't do anything when I try to start debugging in WSL

### ISSUE THREAD

**Issue by cmellazchy** [jborean93/vscode-ansibug#3]
Amazing project! Thanks for working on this. I've been wishing for something like this for a long time.

I am working on WSL. I've opened my ansible project with VSCode. Please find what I've done below:
```
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxxx/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxxx/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```
1. Installed the extension from [marketplace](https://marketplace.visualstudio.com/items?itemName=jborean.ansibug).
2. Installed ansibug using `python3 -m pip install ansibug`.
3. Created Launch configuration following the [docs](https://ansible-community.github.io/ansibug/#:~:text=for%20example%20the%20Ansible%3A%20Launch%20Current%20File%20is%20a%20template%20that%20can%20be%20used%20to%20debug%20the%20current%20playbook%20file%20opened%20in%20the%20editor.).
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Ansibug: Launch Current File",
            "type": "ansible",
            "request": "launch",
            "playbook": "${file}",
            "cwd": "${cwd}",
        }
    ]
}
```
4. I open one of my playbooks and press F5/Start Debugging.
5. The Debugger actions floating bar appears for a second and then disappears. (same with the loader on the debug section)
6. Nothing happens, no new integrated shell is spawn as seen in the demo GIF.

**Comment by jborean93** [comment]
Thanks for the kind words. I've just opened up my test WSL host again and it seems like I have the same problem. I'll have to play around to see what might be happening here as I can manually launch a playbook run with `python -m ansibug listen main.yml` but I can't launch from the extension or attach to my manually launched ansibug run.

**Comment by jborean93** [comment]
At a guess it seems like the debug adapter executable is failing to start. Unfortunately https://github.com/microsoft/vscode/issues/108145 was closed which makes it hard for this extension to get the stderr from the failure to figure out why it actually failed.

In my case it seems like the environment that `python -m ansibug dap` was being run didn't have the env vars needed to find the `ansibug` module so was failing instantly. You could try setting the `ansibug.interpreterPath` setting to the absolute path where `ansibug` and `ansible` are installed on and see if that helps.

I'll need to look into ways of improving this problem so that the error is actually clear but I'm fairly new to typescript so it might take some time.

**Comment by jborean93** [comment]
I've just merged which fixed up the available scopes of the Python interpreter path allowing it to be set on a window level as well as introduce a basic import test before returning the DAP object. While this isn't perfect it can now verify if Python and `ansibug` are actually importable and usable and return an error if not. For example in WSL when I didn't have the `ansibug.interpreterPath` set it would default to an env where `ansibug` was not installed and thus not available.

![image](https://github.com/jborean93/vscode-ansibug/assets/8462645/e3ab81ca-afe0-4223-aff7-72e01bfb90ff)

While this doesn't fix your problem it should hopefully tell you what went wrong when it tried to start `ansibug`.

**Comment by jborean93** [comment]
A new version has been published, hopefully that can narrow down the problem for you.

**Comment by cmellazchy** [comment]
Thanks for following up. I've installed the new version and now it shows the following error when I try to debug.  

![image](https://github.com/jborean93/vscode-ansibug/assets/92443311/6a883e36-0d4a-4e2b-b344-96fde806e7fc)

**Comment by jborean93** [comment]
Hmm that error means `python` does not exist in the `PATH`. A temporary fix would be to add a symlink for `python3` to `python`.

**Comment by cmellazchy** [comment]
Thanks for the workaround, it's running as expected now! I'm on Ubuntu 22.04 and it doesn't have an older version of `python` that is required by the OS already mapped. So, I've created a symlink as per your comment.  
```
sudo ln -sf /usr/bin/python3 /usr/bin/python
```
Will `ansibug` work if the `python` command pointed to python2.7 interpreter? I'm wondering this because the older versions of ubuntu must still have `python` command point to python2.7 interpreter.

Time to wield my newfound power.

**Comment by jborean93** [comment]
Thanks for confirming, I really appreciate you trying this out and sharing these problems.

I've opened https://github.com/jborean93/vscode-ansibug/pull/6 which should improve the interpreter selection logic here to favour `python3` over `python` but still support both. Setting the explicit `ansibug.interpreterPath` should also now just use that literal path.

Here is the vsix inside the zip from https://github.com/jborean93/vscode-ansibug/pull/6 you can try out if you wish but there's no expectation for you to do so:

[vsix.zip](https://github.com/jborean93/vscode-ansibug/files/15195734/vsix.zip)

> I'm wondering if ansibug would work if the python command pointed to python2.7 interpreter

It won't work if it's using Python 2.x as it uses syntax that is only valid in Python 3. I just defaulted to `python` due to muscle memory where I still have `python` pointed to my current interpreter selected by `pyenv`.
